version: '3.4'
services:
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=19411
    ports:
    - 5775:5775/udp
    - 6831:6831/udp
    - 6832:6832/udp
    - 5778:5778
    - 16686:16686
    - 14268:14268
    - 19411:19411    

  grafana:
    image: grafana/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=password1
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    depends_on:
      - jaeger
      - prometheus

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./prometheus_data:/prometheus_data
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always
  
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
     - ./loki/loki.yaml:/etc/config/loki.yaml
    entrypoint:
     - /usr/bin/loki
     - -config.file=/etc/config/loki.yaml
     
  mssql:
    build:
      context: .
      dockerfile: sqlserver/Dockerfile
    environment:
      - SA_PASSWORD=P@55w0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - ${SQL_PORT:-1433}:1433
