{
 "title": "DotNet Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of events processed.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_threads__threads_", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_memory_usage_By", "legendFormat": "Memory bytes" }
   ]
  },
  {
   "title": "HTTP request Timeline",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "dls_dotnet_telemetry_receiver_http_event_processed_count",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "description": "The number of HTTP request received",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dls_dotnet_telemetry_receiver_http_event_processed_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}